### ISSUE TITLE
Gem corrupt

### ISSUE THREAD

**Issue by dshalvardjiev** [hujiko/c_GPIO#1]
Hey,

Thank you for your efforts in creating this gem.

It looks like the gem (all versions tested) is corrupt for some reason (does not contain all neccessary files).
As a side note, it might be good to include a manual installation procedure to the Readme.

Thanks!

**Comment by johansmitsnl** [comment]
This is still an issue

**Comment by hujiko** [comment]
Hey, sorry for taking that much time to respond. I totally forgot about this gem.

Do you get any error message / Stack trace? On which step does it not work?
When you install it, or when you try to use it?

**Comment by johansmitsnl** [comment]
When you download the gem and you look in the directory `lib` you see that there is no file.
You should include the lib directory in your gemspec and therefore the require fails in your code.

Example:
```ruby
s.files        = Dir["CHANGELOG.md", "MIT-LICENSE", "README.md", "lib/**/*"]
s.require_path = "lib"
```

**Comment by hujiko** [comment]
Added that in 0.0.6.

Does it work now for you?

**Comment by johansmitsnl** [comment]
No not yet:

```ruby
require 'c_gpio'
LoadError: cannot load such file -- c_gpio/gpio
from ./vendor/bundle/ruby/2.3.0/gems/c_gpio-0.0.6/lib/c_gpio.rb:5:in `require'
```

**Comment by hujiko** [comment]
At least requiring should work now.

But I don't have a pi here atm, so I can not test, if actually setting IO-Values will work.

**Comment by johansmitsnl** [comment]
Your 0.0.7 release in commit ee8f1ff443347ba00b23cf837fe4462673e4e8f9 fixed the issue :+1:

**Comment by johansmitsnl** [comment]
You may close the issue
