### ISSUE TITLE
mounting GPIO pin not possible

### ISSUE THREAD

**Issue by daBee** [hujiko/c_GPIO#2]
I can't seem to get a test to work using this library on a `Raspberry Pi Zero 2 W`.  

```
l = GPIO::Led.new(8)
5.times do 
  l.turn_on!
  puts "flash"
  sleep 2
  l.turn_off!
  sleep 2
end
```

Error:
```
### flash.rb 2022_Mar_16 20:03
Traceback (most recent call last):
	2: from flash.rb:16:in `<main>'
	1: from flash.rb:16:in `new'
flash.rb:16:in `initialize': Could not open GPIO connection - mounting GPIO pin not possible (ArgumentError)
```

Tried pins 2, 8, and 7.  I don't think the port choice makes much of a difference, though.  I could be wrong.

**Comment by hujiko** [comment]
The port choice should not make any difference.

internally, the gem just writes to
`/sys/class/gpio/gpio8/direction` to declare this pin as an "output" ping.
It does that with the permissions of the user that executes the program. (And there is no error handling)

Could it be, that the user, you run your script as, is not allowed to write to that path?

**Comment by daBee** [comment]
I don't even remember what machine I was using.  This was almost a year ago.
